# This file overrides the default configurations of rubocop. For example, Method
# length has been increased to 15 lines.

MethodLength:
  Max: 15


AllCops:
    Include:
      - '**/Rakefile'
      - '**/config.ru'
    Exclude:
      - 'bin/**/*'
      - 'config/**/*'
      - 'db/**/*'

