# This file overrides the default configurations of rubocop. For example, Method
# length has been increased to 15 lines.

MethodLength:
  Max: 15


AllCops:
    Include:
      - '**/Rakefile'
      - '**/config.ru'
      - 'Gemfile'
      - 'Rakefile'
    Exclude:
      - 'bin/**/*'
      - 'config/**/*'
      - 'db/**/*'
      - 'test/*'


# After I received the following, I checked the behaviour of rubymine's
#autoindentation, which was aligning the parameters. Also, this was
#conflicting with alignment rul with rubocop as well. Thus, disabling this check.
#
# app/helpers/application_helper.rb:21:11: C: Indent the first parameter
# one step more than the start of the previous line.
#          image_path("Favicon/apple-touch-icon-#{size_squared}.png"),

Style/FirstParameterIndentation:
#  Description: 'Checks the indentation of the first parameter in a method call.'
  Enabled: false