language: ruby
rvm:
 - "2.2.3"

# After performing these steps , the build is passing in Travis
# http://docs.travis-ci.com/user/database-setup/#MySQL
services:
  - mysql

before_script:
  - mysql -e 'create database learn_jquery_test;'

  # https://github.com/travis-ci/travis-ci/issues/2190
  # http://docs.travis-ci.com/user/gui-and-headless-browsers
  # /#Using-xvfb-to-Run-Tests-That-Require-a-GUI
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec


# http://docs.travis-ci.com/user/code-climate/
# and https://codeclimate.com/repos/563b63326956804cc10010ae/coverage_setup

addons:
    code_climate:
        repo_token: bd1ac43f2e67a4c5e8277958cc5a21c34bcc4482cdf2c77166e8a674fa83349e